;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="LoadingScreen.Progression.EarlyGame",DevComment="")
+GameplayTagList=(Tag="LoadingScreen.Progression.EndGame",DevComment="")
+GameplayTagList=(Tag="LoadingScreen.Progression.LateGame",DevComment="")
+GameplayTagList=(Tag="LoadingScreen.Progression.MidGame",DevComment="")
+GameplayTagList=(Tag="LoadingScreen.Situation.DyingFrequently",DevComment="")
+GameplayTagList=(Tag="LoadingScreen.Situation.IdleInHub",DevComment="")
+GameplayTagList=(Tag="LoadingScreen.Situation.LowResources",DevComment="")
+GameplayTagList=(Tag="LoadingScreen.Situation.MissingSideQuests",DevComment="")
+GameplayTagList=(Tag="LoadingScreen.Weapon.Magic",DevComment="")
+GameplayTagList=(Tag="LoadingScreen.Weapon.Melee",DevComment="")
+GameplayTagList=(Tag="LoadingScreen.Weapon.Ranged",DevComment="")
+GameplayTagList=(Tag="LoadingScreen.Weapon.Unarmed",DevComment="")

